config/routes.rb
Rails4TwitterClone::Application.routes.draw do

  root 'static_pages#home'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :tweets,        only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  get    'signup'   => 'users#new'
  get    'signin'   => 'sessions#new'
  delete 'signout'  => 'sessions#destroy'
  get    'about'    => 'static_pages#about'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if signed_in?
      @tweet  = current_user.tweets.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def about
  end
end

app/views/static_pages/about.html.slim
h1 About
p Twitter clone app built with Ruby on Rails. See more details on <a href="https://github.com/toshimaru/Rails-4-Twitter-Clone">Github</a>.
p Author: <a href="https://twitter.com/toshimaru_e"> toshimaru</a>

app/views/static_pages/home.html.slim
.row
  - if signed_in?
    - provide(:title, 'Home')
    aside.col-md-4
      section
        = render 'shared/user_info'

    div.col-md-8
      .timeline
        h2.title Tweets
        = render 'shared/feed'

  - else
    - provide(:title, 'Welcome')
    div.col-md-12.one-col
      h1 Welcome to Twitter Clone
      p Start a conversation, explore your interests, and be in the know.

      = link_to 'Sign up', signup_path, class: "btn btn-primary"
      = link_to 'Sign in', signin_path, class: "btn btn-default"