config/routes.rb
Rails4TwitterClone::Application.routes.draw do

  root 'static_pages#home'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :tweets,        only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  get    'signup'   => 'users#new'
  get    'signin'   => 'sessions#new'
  delete 'signout'  => 'sessions#destroy'
  get    'about'    => 'static_pages#about'

end

app/views/layouts/_footer.html.slim
hr

footer.footer
  = link_to "About", about_path

app/views/layouts/_header.html.slim
.navbar.navbar-inverse.navbar-fixed-top role="navigation"
  .container
    .navbar-header
      a.navbar-brand href="/" Twitter Clone
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    .navbar-collapse.collapse
      ul.nav.navbar-nav.navbar-right
        - if signed_in?
          li = link_to "Users",  users_path
          li = link_to "Profile", user_path(current_user)
          li = link_to "All tweets", tweets_path
          li = link_to "Setting", edit_user_path(current_user)
          li = link_to "Sign out", signout_path, method: "delete"
        - else
          - unless params[:controller] == 'static_pages'
            li = link_to "Users",  users_path
            li = link_to "All tweets", tweets_path
            li = link_to "Sign In", signin_path

app/views/layouts/application.html.slim
DOCTYPE html

html
  head
    title = full_title(yield(:title))
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        div class="alert alert-#{key}"
          = value
      = yield
      = render 'layouts/footer'
     